# Generated by Django 3.2.5 on 2021-07-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
